from enum import Enum

UMPIRE_SCORECARD_GAMES_URL = "https://umpscorecards.com/api/games?startDate={start_date}&endDate={end_date}&seasonType={game_type}&team={team}"
UMPIRES_URL = "https://umpscorecards.com/api/umpires/?&season_type={season_type}&start_date={start_date}&end_date={end_date}&team1={home_team}-h&team2={away_team}-a&_=1739746115431"
TEAMS_URL = "https://umpscorecards.com/api/teams/?&season_type={season_type}&start_date={start_date}&end_date={end_date}&umpire={umpire_name}&team={team}&ha={home_away}&venue={stadium}&_=1739746372270"


class UmpireScorecardTeams(Enum):
    ALL = "*"
    DIAMONDBACKS = "AZ"
    ATHLETICS = "ATH"
    BRAVES = "ATL"
    ORIOLES = "BAL"
    RED_SOX = "BOS"
    CUBS = "CHC"
    REDS = "CIN"
    WHITE_SOX = "CWS"
    GAURDIANS = "CLE"
    ROCKIES = "COL"
    ASTROS = "HOU"
    ROYALS = "KC"
    ANGELS = "LAA"
    DODGERS = "LAD"
    MARLINS = "MIA"
    BREWERS = "MIL"
    TWINS = "MIN"
    METS = "NYM"
    YANKEES = "NYY"
    PHILLIES = "PHI"
    PIRATES = "PIT"
    PADRES = "SD"
    MARINERS = "SEA"
    GIANTS = "SF"
    CARDINALS = "STL"
    RAYS = "TB"
    RANGERS = "TEX"
    BLUE_JAYS = "TOR"
    NATIONALS = "WSH"
